### 0-1. 회원가입 (테스트용 계정 생성)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "logtest@test.com",
  "password": "Password123!",
  "userRole": "USER",
  "nickname": "로그테스터"
}

### 0-2. 로그인 (토큰 발급 받기 및 자동 저장)
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "logtest@test.com",
  "password": "Password123!"
}

> {%
    client.global.set("auth_token", response.body.bearerToken);
%}

### 1. 매니저 등록 실패 테스트 (존재하지 않는 일정 9999번에 매니저 등록 시도)
# 이 요청은 "Todo not found" 에러가 발생하며 서버에서는 롤백(Rollback)이 일어납니다.
# 하지만 AOP와 REQUIRES_NEW 덕분에 logs 테이블에는 매니저 등록 시도 로그가 저장되어야 합니다!
POST http://localhost:8080/todos/9999/managers
Content-Type: application/json
Authorization: {{auth_token}}

{
  "managerUserId": 2
}

### 2. 매니저 등록 실패 테스트 2 (존재하지 않는 유저를 매니저로 등록 시도)
# 일정이 있더라도 매니저 유저가 없으면 에러가 납니다. 이것도 로그가 남아야 합니다.
# (미리 1번 일정을 만들어 두셨다고 가정합니다)
POST http://localhost:8080/todos/1/managers
Content-Type: application/json
Authorization: {{auth_token}}

{
  "managerUserId": 9999
}
