### 1. 테스트 유저 생성 (회원가입)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "nplus1_test@example.com",
  "password": "Password123!",
  "userRole": "USER",
  "nickname": "엔플러스원"
}

> {%
    client.global.set("token", response.body.bearerToken);
%}


### 2. 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "nplus1_test@example.com",
  "password": "Password123!"
}

> {%
    client.global.set("token", response.body.bearerToken);
%}


### 3. 새로운 할 일(Todo) 생성
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: {{token}}

{
  "title": "N+1 테스트용 할 일",
  "contents": "댓글을 여러 개 달아봅시다."
}

> {%
    client.global.set("todoId", response.body.id);
%}


### 4. 첫 번째 댓글 작성
POST http://localhost:8080/todos/{{todoId}}/comments
Content-Type: application/json
Authorization: {{token}}

{
  "contents": "첫 번째 댓글입니다!"
}


### 5. 두 번째 댓글 작성
POST http://localhost:8080/todos/{{todoId}}/comments
Content-Type: application/json
Authorization: {{token}}

{
  "contents": "두 번째 댓글입니다!"
}


### 6. 세 번째 댓글 작성
POST http://localhost:8080/todos/{{todoId}}/comments
Content-Type: application/json
Authorization: {{token}}

{
  "contents": "세 번째 댓글입니다!"
}


### 7. 댓글 목록 조회 (N+1 해결 확인용)
# 이 API를 호출한 뒤 IntelliJ의 실행(Run) 탭 콘솔 로그를 확인하세요!
# Hibernate SQL 로그에 SELECT 쿼리가 딱 1번만 나가면 N+1 문제가 해결된 것입니다.
GET http://localhost:8080/todos/{{todoId}}/comments
Authorization: {{token}}
